server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.123.101:1521:orcl11
    username: hr
    password: tiger

  security:    oauth2:      client:
      
        provider:
          naver: # 네이버는 OAuth2 라이브러리에 프로바이더로 등록이 되어있지않다 등록을 해줘야 한다.
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 이 주소로 요청시 네이버 로그인창이 뜸
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 만들려면 이 주소로 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # 로그인한 사용자의 프로필 정보를 받으려면 이 주소로 요청
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌                  registration:          google:
            client-id: 579235171085-frj84tv0gjl7dmme498gj65jjqoksd1a.apps.googleusercontent.com
            client-secret: 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
            scope:            - email
            - profile
          
          facebook:
            client-id: 804592287464947
            client-secret: b0d1b1c48eef4d0d1a479c4fa36ae4a6
            scope:
            - email
            - public_profile
            
          naver:
            client-id: FYD4maKXAUPLyn_tenrY
            client-secret: x4iiEosFjS
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            


mybatis:
  type-aliases-package: com.example.security1.model
  mapper-locations: classpath:mapper/*.xml
      
